Project 1: Setup and mobile version skeleton
Loltolo-Lesapiti/Portfolio-Website pull request #1
Opened 2022-04-26 10:52 UTC by Loltolo-Lesapiti

A project to create a personal portfolio website.

2022-04-26 14:22 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Loltolo-Lesapiti👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
- [ ] On line 26 please change `<p>`  with `<hx>` tag, You can use h2, h3, h4.... This will make sure the code is semantic and follows best practices.
- [ ] Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] I would recommend deleting the `test.md` file from this project. Because this file is not part of this project. Removing it will make your project directory clean.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 14:22 UTC, thecodechaser commented on index.html
>        <p class="intro">I'm Petro Glad to See You</p>
- [ ] Please change this `<p>` tag to `<h1>`, This will make the code semantic. The main headline of the webpage should be the heading and `<h1>` is good for SEO. Read more [HERE](https://www.socialhive.com.au/blog/2021/june/h1-tags/#:~:text=H1%20tags%20are%20an%20important,big%20difference%20to%20SEO%20performance.).

2022-04-26 14:22 UTC, thecodechaser commented on index.html
>      <div class="main-content">
- [ ] Please change this `<div>` tag to `<main>` tag. This will make sure the code follows best practices and is semantic.

2022-04-26 14:22 UTC, thecodechaser commented on index.html
> +  <div class="container" >
- [ ] Please remove the top margin from the header section to match your design with the Figma design.

### See the image for reference 

![image](https://user-images.githubusercontent.com/83803414/165319630-48d9b1e8-fe76-4f28-a768-b88e63c15734.png)

2022-04-26 14:22 UTC, thecodechaser commented on index.html
>      <div class="main-content">
- [ ] The background image you are using for your hero section is blank. Please use the correct background image and make sure it matches the Figma design

### Your design

![image](https://user-images.githubusercontent.com/83803414/165320403-797a4330-cefc-4f7e-b414-0c019bf89408.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/165320475-435c4eb9-7ac1-4ac5-9cfd-8ed5310c0220.png)

2022-04-27 06:29 UTC, danmainah requested changes
Hi @Loltolo-Lesapiti, 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used


 # Required Changes ♻️

- [ ] You have not made any changes as requested by the reviewer, kindly make them before asking for another review.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 11:13 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Loltolo-Lesapiti 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 11:13 UTC, thecodechaser commented on index.html
>      <div class="main-content">
- [ ] As requested by me previously Please change this `<div>` tag to the `<main>` tag. This will make sure the code follows best practices and is semantic.
  - You changed the wrong `<div>`. We should not include `<header>` inside `<main>` tag. `<main>` should only be responsible for the hero section of the website.

2022-04-27 11:13 UTC, thecodechaser commented on index.html
> +  <main class="container" >
- [ ] As requested by me previously Please remove the top margin from the header section to match your design with the Figma design.

### See the image for reference 

![image](https://user-images.githubusercontent.com/83803414/165319630-48d9b1e8-fe76-4f28-a768-b88e63c15734.png)

2022-04-27 11:13 UTC, thecodechaser commented on index.html
> +      <i class="material-icons">menu</i>
- [ ] As requested by me previously, please use the correct color for your hamburger icon and make sure it matches the design.
  - You can get the properties of elements from the Figma design, Click on the element, and from the right side window, you can check the element property.

### Your design

![image](https://user-images.githubusercontent.com/83803414/165319912-01826b28-d63f-4eab-966a-93ba7bd7a052.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/165319955-3aeefa4c-d421-4ef3-aecd-3181a24b5b85.png)

2022-04-27 11:13 UTC, thecodechaser commented on index.html
>      <div class="main-content">
- [ ] As requested by me previously The background image you are using for your hero section is blank. Please use the correct background image and make sure it matches the Figma design.
   - You can download the background images from the Figma template, click on the image, and export it from the right side window.

### Your design

![image](https://user-images.githubusercontent.com/83803414/165320403-797a4330-cefc-4f7e-b414-0c019bf89408.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/165320475-435c4eb9-7ac1-4ac5-9cfd-8ed5310c0220.png)

2022-04-27 11:13 UTC, thecodechaser commented on index.html
> +      <h1 class="intro">I'm Petro Glad to See You</h1>
- [ ] As requested by me previously, please use the correct font-weight, front family, and font-size for your hero section texts. You can check the font properties in Figma click on the element and from the right side of the window, you can check the element properties.

### Your design

![image](https://user-images.githubusercontent.com/83803414/165320953-41b42a7e-45fe-4f3e-a545-fbbfbf6b55e4.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/165321015-d9b2d645-13d7-463f-a612-d52a359c5303.png)

2022-04-27 11:13 UTC, thecodechaser commented on index.html
> +      <h4>Let's connect</h4>
- [ ] As requested by me previously, please place a margin between the "LET'S CONNECT" heading and social media icons, Use uppercase, Use the correct color for this heading and make sure it matches with the Figma design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/165321445-4287eca6-64f3-417b-beac-491408eb35bf.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/165321487-31d1d634-c19f-4989-a81f-225642201113.png)

2022-04-27 19:04 UTC, koomekevo requested changes
Hi @Loltolo-Lesapiti , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly implement the changes as requested by previous reviewers. 
- [ ] Please adhere to the design of the Figma template you have chosen. The below screenshot is the required design.

![loltolocorrect](https://user-images.githubusercontent.com/87413774/165600427-054d3707-0ac4-4e17-855e-b4282960baf9.png)

- [ ] The below screenshot is your design

![loltolowrong](https://user-images.githubusercontent.com/87413774/165600597-75239c06-82ce-403c-9fcd-091603ec048d.png)






## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 09:50 UTC, Loltolo-Lesapiti commented
@thecodechaser please check implemented the changes, please check now.

2022-04-28 10:31 UTC, topeogunleye commented
> @thecodechaser please check implemented the changes, please check now.

@Loltolo-Lesapiti, your h1 is supposed to have `color: #172B4D;` . Please make changes

2022-04-28 10:42 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @Loltolo-Lesapiti,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
>- [ ] Your Logo and Hamburger menu are too close to the edges compared to the Template Design. I kindly  suggest that you make changes:
>- [ ] Your h1 i.e main-title is supposed to have color: #172B4D; and not black . Please make changes

| Your Design  | Template Design |
| ------------- | ------------- |
| ![Screenshot from 2022-04-28 11-32-59](https://user-images.githubusercontent.com/52934128/165734968-95d94f76-a1d4-4d10-bc1a-28ae3b9114d1.png)  | ![Screenshot from 2022-04-28 11-33-07](https://user-images.githubusercontent.com/52934128/165735002-8b89f567-40bc-49d1-bbc7-eddd7d6ac1f3.png)  |

> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-28 10:49 UTC, topeogunleye requested changes

2022-04-28 10:49 UTC, topeogunleye commented on style.css
> +    color: rgb(6, 9, 15);
- [ ]  Your `h1` i.e main-title is supposed to have `color: #172B4D;` and not rgb(6, 9, 15);. Please kindly make changes

2022-04-28 11:02 UTC, Loltolo-Lesapiti commented on style.css
> +    color: rgb(6, 9, 15);
@topeogunleye . I changed. Check now.

2022-04-28 12:13 UTC, topeogunleye commented on style.css
> +    color: rgb(6, 9, 15);
@Loltolo-Lesapiti. I will check :+1:

2022-04-28 12:16 UTC, topeogunleye approved these changes
### Hi @Loltolo-Lesapiti, 

# Status: Approved ✔️
Excellent job on making the required changes I requested in the previous review. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 12:26 UTC, merged